#!/usr/bin/with-contenv bash

postgres_host="${DB_HOST:-postgres}"
postgres_port="${DB_PORT:-5432}"
postgres_user="${DB_USER:-spotweb}"
postgres_pass="${DB_PASS:-spotweb}"
postgres_db="${DB_NAME:-spotweb}"

# upgrade the db
s6-setuidgid abc php /app/bin/upgrade-db.php

if [ $(PGPASSWORD=$postgres_pass psql -t -U $postgres_user -h $postgres_host -p $postgres_port -d $postgres_db -c "select count(*) from users where username = 'admin' and lastlogin = 0;") -eq 1 ];
then
    echo "Admin has not logged in, set default password"
    s6-setuidgid abc php /app/bin/upgrade-db.php --reset-password admin
else
    echo "Admin has already logged in, no need to set default password"
fi
